### ISSUE TITLE
Folder name

### ISSUE THREAD

**Issue by manake** [humanmade/WordPress-Importer#84]
Current folder name: WordPress-Importer
Proposed new folder name: wordpress-importer

And also it seems that installing this version of plugin requires removal of the previous version because the folders are named exactly the same way. The installation instructions should be updated then as it's not possible to just "deactivate" the previous plugin. The folder name has to be changed or the previous folder has to be deleted.

**Comment by rmccue** [comment]
The folder naming is completely up to you when you clone the repo; `WordPress-Importer` is the default because that's the name of the repo, but you can call it whatever you want. `wordpress-importer-v2` is fine, for example.

The plan is that eventually, this will supersede v1 in any case, so it doesn't make sense to rename it.
