### ISSUE TITLE
Export side not exporting all records

### ISSUE THREAD

**Issue by donty** [humanmade/WordPress-Importer#86]
This has been a really useful plugin for moving in/out of multisite but right now we seem to have hit limits somewhere.

When I export custom posts from WP (orders from Marketpress) it seems only to do about 200 odd starting at the earliest date. It successfully imports all that were exported. 

The export file size is 4MB so it's not hitting file size limits on PHP or WP. Any ideas? Any option limiting the number of records? We need 1000+ records and I presume this is not uncommon.

**Comment by rmccue** [comment]
Sorry for the delayed reply here @donty. The Export part is part of WordPress itself, so not covered under this repo; you can [report it on the WordPress Trac](https://core.trac.wordpress.org/) instead.

It's possible that the problem is the time limit in PHP. This is 30 seconds by default. You could potentially run an export using wp-cli instead?
